#!/usr/bin/env python3
"""Simulate the pipeline output to demonstrate what each stage produces."""

import json
from pathlib import Path
import shutil

def simulate_pipeline():
    """Create example output files that the pipeline would generate."""
    
    # Create demo hero directory
    hero_dir = Path("heroes/tung_sahur_demo")
    hero_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"🎭 Creating simulated pipeline output in: {hero_dir}")
    print("=" * 60)
    
    # 1. Copy input image
    input_image = Path("heroes/tungtungtungtungtungtungtungtungtung_sahur/image.png")
    if input_image.exists():
        shutil.copy2(input_image, hero_dir / "input_image.png")
        print("✅ 1. Input image copied")
    else:
        print("❌ 1. Input image not found")
    
    # 2. Generate 3D mesh (OBJ file)
    mesh_content = '''# Simple Humanoid Mesh
# Generated by Tung Playground Mock Generator

# Vertices (head, torso, arms, legs)
v 0.0 1.8 0.0      # Head top
v 0.0 1.6 0.0      # Head bottom
v 0.15 1.7 0.0     # Head side
v -0.15 1.7 0.0    # Head side

v 0.0 1.4 0.0      # Neck
v 0.2 1.2 0.0      # Shoulder right
v -0.2 1.2 0.0     # Shoulder left
v 0.2 0.8 0.0      # Torso right
v -0.2 0.8 0.0     # Torso left
v 0.0 0.6 0.0      # Torso bottom

v 0.4 1.1 0.0      # Right arm upper
v 0.4 0.7 0.0      # Right arm lower
v 0.4 0.4 0.0      # Right hand
v -0.4 1.1 0.0     # Left arm upper
v -0.4 0.7 0.0     # Left arm lower
v -0.4 0.4 0.0     # Left hand

v 0.1 0.6 0.0      # Right hip
v 0.1 0.2 0.0      # Right knee
v 0.1 -0.2 0.0     # Right ankle
v 0.1 -0.3 0.0     # Right foot
v -0.1 0.6 0.0     # Left hip
v -0.1 0.2 0.0     # Left knee
v -0.1 -0.2 0.0    # Left ankle
v -0.1 -0.3 0.0    # Left foot

# Simple faces (triangular)
f 1 2 3
f 1 3 4
f 2 4 3
f 2 1 4

f 5 6 7
f 6 8 9
f 7 9 8
f 8 10 9
'''
    
    with open(hero_dir / "generated_mesh.obj", 'w') as f:
        f.write(mesh_content)
    print("✅ 2. Generated 3D mesh (generated_mesh.obj)")
    
    # 3. Create parts directory with decomposed parts
    parts_dir = hero_dir / "parts"
    parts_dir.mkdir(exist_ok=True)
    
    parts = {
        "head.obj": "# Part: head\\nv 0.0 1.7 0.1\\nv 0.1 1.7 0.0\\nv 0.0 1.7 -0.1\\nv -0.1 1.7 0.0\\nf 1 2 3\\nf 1 3 4\\n",
        "torso.obj": "# Part: torso\\nv 0.2 1.0 0.1\\nv 0.2 1.0 -0.1\\nv -0.2 1.0 -0.1\\nv -0.2 1.0 0.1\\nf 1 2 3\\nf 1 3 4\\n",
        "arms.obj": "# Part: arms\\nv 0.4 0.8 0.0\\nv 0.4 0.6 0.0\\nv -0.4 0.6 0.0\\nv -0.4 0.8 0.0\\nf 1 2 3\\nf 1 3 4\\n",
        "legs.obj": "# Part: legs\\nv 0.1 0.0 0.1\\nv 0.1 0.0 -0.1\\nv -0.1 0.0 -0.1\\nv -0.1 0.0 0.1\\nf 1 2 3\\nf 1 3 4\\n"
    }
    
    for part_name, content in parts.items():
        with open(parts_dir / part_name, 'w') as f:
            f.write(content)
    
    print(f"✅ 3. Decomposed into {len(parts)} parts: {list(parts.keys())}")
    
    # 4. Create skeleton JSON
    skeleton_data = {
        "skeleton_type": "biped",
        "joint_count": 20,
        "bone_count": 19,
        "joints": {
            "root": {"position": [0.0, 0.0, 0.0], "parent": None, "children": ["pelvis"]},
            "pelvis": {"position": [0.0, 0.8, 0.0], "parent": "root", "children": ["spine", "left_hip", "right_hip"]},
            "spine": {"position": [0.0, 1.0, 0.0], "parent": "pelvis", "children": ["chest"]},
            "chest": {"position": [0.0, 1.2, 0.0], "parent": "spine", "children": ["neck", "left_shoulder", "right_shoulder"]},
            "neck": {"position": [0.0, 1.5, 0.0], "parent": "chest", "children": ["head"]},
            "head": {"position": [0.0, 1.7, 0.0], "parent": "neck", "children": []},
            "left_shoulder": {"position": [-0.2, 1.3, 0.0], "parent": "chest", "children": ["left_upper_arm"]},
            "left_upper_arm": {"position": [-0.3, 1.1, 0.0], "parent": "left_shoulder", "children": ["left_lower_arm"]},
            "left_lower_arm": {"position": [-0.3, 0.7, 0.0], "parent": "left_upper_arm", "children": ["left_hand"]},
            "left_hand": {"position": [-0.3, 0.4, 0.0], "parent": "left_lower_arm", "children": []},
            "right_shoulder": {"position": [0.2, 1.3, 0.0], "parent": "chest", "children": ["right_upper_arm"]},
            "right_upper_arm": {"position": [0.3, 1.1, 0.0], "parent": "right_shoulder", "children": ["right_lower_arm"]},
            "right_lower_arm": {"position": [0.3, 0.7, 0.0], "parent": "right_upper_arm", "children": ["right_hand"]},
            "right_hand": {"position": [0.3, 0.4, 0.0], "parent": "right_lower_arm", "children": []},
            "left_hip": {"position": [-0.1, 0.7, 0.0], "parent": "pelvis", "children": ["left_upper_leg"]},
            "left_upper_leg": {"position": [-0.1, 0.4, 0.0], "parent": "left_hip", "children": ["left_lower_leg"]},
            "left_lower_leg": {"position": [-0.1, 0.0, 0.0], "parent": "left_upper_leg", "children": ["left_foot"]},
            "left_foot": {"position": [-0.1, -0.3, 0.0], "parent": "left_lower_leg", "children": []},
            "right_hip": {"position": [0.1, 0.7, 0.0], "parent": "pelvis", "children": ["right_upper_leg"]},
            "right_upper_leg": {"position": [0.1, 0.4, 0.0], "parent": "right_hip", "children": ["right_lower_leg"]},
            "right_lower_leg": {"position": [0.1, 0.0, 0.0], "parent": "right_upper_leg", "children": ["right_foot"]},
            "right_foot": {"position": [0.1, -0.3, 0.0], "parent": "right_lower_leg", "children": []}
        },
        "metadata": {
            "generated_by": "MockRigger",
            "version": "1.0.0",
            "coordinate_system": "Y-up",
            "units": "meters"
        }
    }
    
    with open(hero_dir / "skeleton.json", 'w') as f:
        json.dump(skeleton_data, f, indent=2)
    print("✅ 4. Generated skeleton with 20 joints and biped hierarchy")
    
    # 5. Create URDF file
    urdf_content = '''<?xml version="1.0"?>
<robot name="tung_hero">

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="generated_mesh.obj" scale="1 1 1"/>
      </geometry>
      <material name="hero_material">
        <color rgba="0.8 0.6 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="generated_mesh.obj" scale="1 1 1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Pelvis Link -->
  <link name="pelvis_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="joint_material">
        <color rgba="0.2 0.2 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Root to Pelvis Joint -->
  <joint name="root_to_pelvis" type="revolute">
    <parent link="base_link"/>
    <child link="pelvis_link"/>
    <origin xyz="0.000 0.800 0.000" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14159" upper="3.14159" effort="100" velocity="10"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

</robot>'''
    
    with open(hero_dir / "robot.urdf", 'w') as f:
        f.write(urdf_content)
    print("✅ 5. Generated URDF with links and joints")
    
    # 6. Create MuJoCo scene
    scene_content = '''<mujoco model="tung_sahur_demo_scene">
  
  <!-- Compiler settings -->
  <compiler angle="radian" coordinate="local" inertiafromgeom="true"/>
  
  <!-- Size and timestep -->
  <size nconmax="50" njmax="100" nstack="300000"/>
  <option timestep="0.002" iterations="50"/>
  
  <!-- Visual settings -->
  <visual>
    <rgba haze="0.3 0.3 0.3 1"/>
    <quality shadowsize="2048"/>
    <map force="0.1" zfar="30"/>
  </visual>
  
  <!-- Default classes -->
  <default>
    <light cutoff="100" exponent="1"/>
    <geom rgba="0.8 0.6 .4 1" margin="0.001" condim="3" conaffinity="1" friction="1 0.1 0.1"/>
    <motor ctrlrange="-1 1" ctrllimited="true"/>
  </default>
  
  <!-- World body -->
  <worldbody>
    <!-- Lighting -->
    <light cutoff="100" diffuse="1 1 1" dir="-0 0 -1.3" directional="true" exponent="1" pos="0 0 1.3" specular=".1 .1 .1"/>
    
    <!-- Ground plane -->
    <geom conaffinity="1" condim="3" name="floor" pos="0 0 0" rgba="0.8 0.9 0.8 1" size="40 40 40" type="plane"/>
    
    <!-- Include hero robot -->
    <body name="tung_sahur_demo" pos="0 0 0.5">
      <geom name="tung_sahur_demo_base" type="box" size="0.1 0.1 0.2" rgba="0.8 0.6 0.2 1"/>
      <joint name="tung_sahur_demo_free" type="free"/>
    </body>
    
    <!-- Additional scene objects -->
    <body name="target" pos="2 0 0.1">
      <geom name="target_geom" type="sphere" size="0.1" rgba="1 0 0 1"/>
    </body>
  </worldbody>
  
</mujoco>'''
    
    with open(hero_dir / "scene.xml", 'w') as f:
        f.write(scene_content)
    print("✅ 6. Generated MuJoCo simulation scene")
    
    # 7. Create trained policy (mock)
    import pickle
    policy_data = {
        "policy_type": "random",
        "algorithm": "ppo",
        "version": "1.0.0",
        "action_space": {"type": "continuous", "shape": [6], "low": [-1.0] * 6, "high": [1.0] * 6},
        "observation_space": {"type": "continuous", "shape": [24], "low": [-10.0] * 24, "high": [10.0] * 24},
        "training_stats": {"episodes": 100, "total_timesteps": 1000000, "final_reward": 342.5, "learning_rate": 0.0003}
    }
    
    with open(hero_dir / "policy.pkl", 'wb') as f:
        pickle.dump(policy_data, f)
    print("✅ 7. Generated trained RL policy")
    
    # 8. Create hero metadata
    hero_metadata = {
        "id": "hero_123456",
        "name": "tung_sahur_demo",
        "status": "ready",
        "created_at": "2025-01-15T12:00:00",
        "updated_at": "2025-01-15T12:05:30",
        "assets": {
            "input_image": "input_image.png",
            "mesh_3d": "generated_mesh.obj",
            "parts": ["parts/head.obj", "parts/torso.obj", "parts/arms.obj", "parts/legs.obj"],
            "skeleton": "skeleton.json",
            "urdf": "robot.urdf",
            "simulation_model": "scene.xml",
            "trained_policy": "policy.pkl",
            "metadata": {
                "generation": {"generator": "mock_generator", "quality_score": 0.85, "vertices": 156, "faces": 280},
                "decomposition": {"decomposer": "mock_decomposer", "part_count": 4, "method": "semantic_splitting"},
                "rigging": {"rigger": "mock_rigger", "joint_count": 20, "bone_count": 19, "skeleton_type": "biped"},
                "urdf": {"generator": "mock_urdf_builder", "link_count": 20, "joint_count": 19, "physics_engine": "mujoco"},
                "simulation": {"adapter": "mock_mujoco_adapter", "environment_type": "mujoco", "timestep": 0.002},
                "training": {"trainer": "mock_trainer", "algorithm": "ppo", "training_episodes": 100, "final_reward": 342.5}
            }
        },
        "processing_log": [
            {"timestamp": "2025-01-15T12:00:00", "stage": "generation", "message": "3D mesh generated successfully"},
            {"timestamp": "2025-01-15T12:01:00", "stage": "decomposition", "message": "Mesh decomposed into 4 parts"},
            {"timestamp": "2025-01-15T12:02:00", "stage": "rigging", "message": "Biped skeleton generated with 20 joints"},
            {"timestamp": "2025-01-15T12:03:00", "stage": "urdf", "message": "URDF generated with complete robot description"},
            {"timestamp": "2025-01-15T12:04:00", "stage": "simulation", "message": "MuJoCo scene created successfully"},
            {"timestamp": "2025-01-15T12:05:30", "stage": "training", "message": "RL policy trained with final reward: 342.5"}
        ]
    }
    
    with open(hero_dir / "hero.json", 'w') as f:
        json.dump(hero_metadata, f, indent=2)
    print("✅ 8. Generated hero metadata")

def show_results():
    """Show the final results."""
    hero_dir = Path("heroes/tung_sahur_demo")
    
    print("\\n🎉 Pipeline Simulation Complete!")
    print("=" * 60)
    print(f"📁 Generated files in {hero_dir}:")
    
    if hero_dir.exists():
        files = list(hero_dir.rglob("*"))
        files.sort()
        
        for file_path in files:
            if file_path.is_file():
                size = file_path.stat().st_size
                rel_path = file_path.relative_to(hero_dir)
                print(f"   📄 {rel_path} ({size} bytes)")
    
    print("\\n🚀 What Each File Represents:")
    print("   • input_image.png - Original character image")
    print("   • generated_mesh.obj - 3D mesh with 24 vertices")
    print("   • parts/ - Decomposed body parts (head, torso, arms, legs)")
    print("   • skeleton.json - Biped skeleton with 20 joints")
    print("   • robot.urdf - Complete robot description for physics")
    print("   • scene.xml - MuJoCo simulation environment")
    print("   • policy.pkl - Trained locomotion policy")
    print("   • hero.json - Complete processing metadata")
    
    print("\\n✨ This demonstrates the complete AIGC hero pipeline!")
    print("   Image → 3D Mesh → Parts → Skeleton → URDF → Simulation → Policy")

if __name__ == "__main__":
    simulate_pipeline()
    show_results()